### ISSUE TITLE
WLR_NO_HARDWARE_CURSORS is deprecated

### ISSUE THREAD

**Issue by totallypredictable** [CachyOS/cachyos-hyprland-settings#11]
As per the issue https://github.com/hyprwm/Hyprland/issues/8036 and [this document](https://wiki.hyprland.org/Nvidia/#environment-variables), forcing software cursors using the `WLR_NO_HARDWARE_CURSORS` environment variable is deprecated. With the latest version of cachyos-hyprland, there's an extreme framerate drop as a result of this `env` no longer being recognized by hyprland. 

Instead, the recommendation is to use `cursor { no_hardware_cursors = true }` config option in `hyprland.conf`.

The `WLR_NO_HARDWARE_CURSORS` env variable is being set by the [Hyprland.sh](https://github.com/CachyOS/cachyos-hyprland-settings/blob/master/etc/profile.d/Hyprland.sh) script, but since it's no longer managed by an `env` variable and rather by a config option, I don't know how to fix the issue myself in this repo. I can only think of setting the config option explicitly/manually in my local config file.

**Comment by Shendisx** [comment]
Fixed in 476d1a64f65317b71334bc781e29e1e441c34fb0. Thanks for pointing it out
