### ISSUE TITLE
Option to switch to `hyprland-nvidia`

### ISSUE THREAD

**Issue by stickyburn** [CachyOS/cachyos-hyprland-settings#5]
Screensharing isn't working and the solution would be to install hyprland-nvidia instead. After doing so, Hyprland can be uninstalled for conflicts, but then SDDM finds no sessions to log into. Could someone help me on adding Hyprland-nvidia? 

Maybe this could be an option during install. Amazing work btw, switched from minimal Artix and very little to complain!! ❤️

**Comment by vnepogodin** [comment]
you can also try to use [xwaylandvideobridge](https://aur.archlinux.org/packages/xwaylandvideobridge-bin) for screenshare

**Comment by stickyburn** [comment]
@vnepogodin thanks for the suggestion! Just tried but no success. I'm on Firefox and tried meets/zoom.
