### ISSUE TITLE
Add nvidia envs

### ISSUE THREAD

**Issue by stickyburn** [CachyOS/cachyos-hyprland-settings#6]
There's a few envs needed to be added for Nvidia GPUs. Without this, the cursor disappears and sometimes Hyprland is unable to boot. Would be great to add these to config if Nvidia is detected.

```
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
```

https://wiki.hyprland.org/Nvidia/

**Comment by vnepogodin** [comment]
These are included
