### ISSUE TITLE
hyprland.sh doesn't seem to be working 

### ISSUE THREAD

**Issue by catbabylon** [CachyOS/cachyos-hyprland-settings#9]
Fresh install on a dell xps 8930 desktop, this machine has Intel UHD Graphics 630 on the board but also has a nvidia GTX 1070 card.
The WLR_NO_HARDWARE_CURSORS=1 variable is not active and no cursor is visible. Manually adding it to /etc/environment fixes the issue but I'm wondering why the script isn't working for me.

**Comment by inffy** [comment]
I think it has been deprecated and needs to be set in hyprland.conf with:

cursor {
    no_hardware_cursors = true
}

**Comment by msmafra** [comment]
> I think it has been deprecated and needs to be set in hyprland.conf with:
> 
> cursor { no_hardware_cursors = true }
> 
> See here https://wiki.hyprland.org/Nvidia/#environment-variables

Since 0.45.0 it can be set to detect automatically with:
```
cursor {
    no_hardware_cursors = 2
}
```
Check here https://wiki.hyprland.org/0.45.0/Configuring/Variables/#cursor
